# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Book' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.6'

  # Pods for Book

  target 'BookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookUITests' do
    # Pods for testing
  end

end
